CREATE DATABASE boscabelereiros;

CREATE TABLE boscabelereiros.Pessoa (
	id				INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	nome			VARCHAR(30) NOT NULL,
	login			VARCHAR(12) NOT NULL UNIQUE,
	senha			VARCHAR(10) NOT NULL,
	email			VARCHAR(30),
	rg				VARCHAR(20),
	cpf				VARCHAR(20),
	telefone_res	VARCHAR(20),
	telefone_cel	VARCHAR(20),

	PRIMARY KEY(id)
)
ENGINE = INNODB;

CREATE TABLE boscabelereiros.Funcionario (
	id				INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	pessoa			INTEGER UNSIGNED NOT NULL,
	salario			FLOAT NOT NULL,
	funcao			VARCHAR(40) NOT NULL,

	PRIMARY KEY(id),
	FOREIGN KEY(pessoa) REFERENCES Pessoa(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)
ENGINE = INNODB;

CREATE TABLE boscabelereiros.Cliente (
	id				INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	pessoa			INTEGER UNSIGNED NOT NULL,

	PRIMARY KEY(id),
	FOREIGN KEY(pessoa) REFERENCES Pessoa(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)
ENGINE = INNODB;

CREATE TABLE boscabelereiros.Servico (
	id				INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	horario			BIGINT UNSIGNED NOT NULL,
	tipo			INTEGER UNSIGNED NOT NULL,
	cliente			INTEGER UNSIGNED NOT NULL,

	PRIMARY KEY(id),
	FOREIGN KEY(cliente) REFERENCES Pessoa(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)
ENGINE = INNODB;

CREATE TABLE boscabelereiros.Produto (
	id				INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	nome			VARCHAR(40) NOT NULL,
	descricao		VARCHAR(50),
	preco			FLOAT,
	imagem			VARCHAR(60),

	PRIMARY KEY(id)
)
ENGINE = INNODB;


